spring.application.name=pitstop-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/pitstop
spring.datasource.username=postgres
spring.datasource.password=Mrstark@007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true