package com.pitstop.pitstop_backend.job;

public enum ProblemType {
    BATTERY_DEAD,
    ENGINE_OVERHEATING,
    ENGINE_WONT_START,
    ENGINE_NOISE,
    OIL_LEAK,
    FLAT_TYRE,
    TYRE_BURST,
    CHAIN_SNAPPED,
    BRAKE_FAILURE,
    BRAKE_NOISE,
    CLUTCH_FAILURE,
    SUSPENSION_DAMAGE,
    HEADLIGHTS_NOT_WORKING,
    ACCIDENT_DAMAGE,
    VEHICLE_STUCK,
    STRANGE_NOISE,
    DONT_KNOW,
    GEAR_STUCK,
    STEERING_LOCKED,
    WARNING_LIGHT
}